### ISSUE TITLE
Spanish translation.

### ISSUE THREAD

**Issue by vidimus** [Crosisdepurger/Mansios#1]
Hello, @CrosisdePurger

There's an user from the Spanish FFG forum that wants to translate your scenario into Spanish. Can he start to translate your scenario? Are you available for update your scenario when the translation finishes?

**Comment by vidimus** [comment]
Hello, @Crosisdepurger , have you read my previous message? (There's an user from the Spanish FFG forum that wants to translate your scenario into Spanish. Can he start to translate your scenario? Are you available for update your scenario when the translation finishes?)

**Comment by Crosisdepurger** [comment]
Howdy. He may translate it, and I will do what I can to assist. 

Sent from Yahoo Mail on Android 
 
  On Thu, Sep 17, 2020 at 17:30, vidimus<notifications@github.com> wrote:   


Hello, @Crosisdepurger , have you read my previous message? (There's an user from the Spanish FFG forum that wants to translate your scenario into Spanish. Can he start to translate your scenario? Are you available for update your scenario when the translation finishes?)

**Comment by vidimus** [comment]
Hello, @Crosisdepurger 

Great. I will tell him. Thanks!

**Comment by vidimus** [comment]
Hello, @Crosisdepurger 

The translation is finished. Now they're testing it. I will contact you again when the file is ready.

**Comment by vidimus** [comment]
Hello, @Crosisdepurger .

After a lot of delays and several issues, the translation is almost done. We had to redone from the scratch, but I will send you it in a few days.

**Comment by vidimus** [comment]
Hello, I finish with the testing. I have created the package with the Spanish translation added to the original file, so you only need to check it and upload to your repository. 

Here's the file and the txt, too, in case you want to make the package by yourself.

[Localization.Spanish.txt](https://github.com/Crosisdepurger/Mansios/files/5636579/Localization.Spanish.txt)



[MutantMadness.zip](https://github.com/Crosisdepurger/Mansios/files/5636589/MutantMadness.zip)

**Comment by vidimus** [comment]
@Crosisdepurger , did you read my previous message? (I forgot to mention you on it).

**Comment by vidimus** [comment]
@Crosisdepurger , any news about the update?

**Comment by vidimus** [comment]
Hello, @Crosisdepurger ?

**Comment by vidimus** [comment]
Do you read this, @Crosisdepurger ?

**Comment by vidimus** [comment]
@Crosisdepurger ?

**Comment by vidimus** [comment]
Hello? @Crosisdepurger ?

**Comment by vidimus** [comment]
Hello, @Crosisdepurger . Any news about updating the scenario with the translation? If you are not able to assist your scenario or repository, you can give permission to a member of the Valkyrie's staff. And he/she will maintain your scenario.

**Comment by vidimus** [comment]
@Crosisdepurger, nothing yet?

**Comment by vidimus** [comment]
@Crosisdepurger 

Here's the new version of the files. I'd skipped an image with some text. Now that one is also localized. You only need to unzip the file and replace your repository files with them. Spanish translation will automatically be added and your scenario will be updated. 

I've translated more than 35 scenarios (you can check it on my repos or asking someone from Valkyrie's staff)
, so you can trust on me. Anyway, if you want to do it by yourself, the txt file is also provided on this post.

Zip with the 3 repository files (to replace the old ones):

[MutantMadness.zip](https://github.com/Crosisdepurger/Mansios/files/5996822/MutantMadness.zip)

Text only:

[Localization.Spanish.txt](https://github.com/Crosisdepurger/Mansios/files/5996826/Localization.Spanish.txt)

**Comment by vidimus** [comment]
Any news, @Crosisdepurger ?

**Comment by vidimus** [comment]
Still nothing, @Crosisdepurger  ?

**Comment by vidimus** [comment]
@Crosisdepurger ?

**Comment by Crosisdepurger** [comment]
Sup I'm off my lazy ass. I replaced the files in the repository,

**Comment by Crosisdepurger** [comment]
I assume I'm supposed to create an issue now so doing so.

**Comment by vidimus** [comment]
> I assume I'm supposed to create an issue now so doing so.

Hello, @Crosisdepurger 
No, it's OK. Translation is available. Thanks for uploading it.

You can close this issue if you want.
